<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_priceKatalogPage</name>
   <tag></tag>
   <elementGuidId>a3357c3c-c7f1-4db0-af65-6e1c3955e861</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='inventory_list']/descendant::div[@class='pricebar'][1]/descendant::*[text()[contains(.,'29.99')]]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
